name: dart_fundamentos
description: projeto referente a inicialização do curso de flutter
version: 1.0.0
homepage: https://capivarias.com.br

environment:
  sdk: '>=2.17.3 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
